// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChUy0c6nHbe5urWFx1pSoRxguV22VJbR4',
    appId: '1:70488794227:web:be3cb804799816b0a6b606',
    messagingSenderId: '70488794227',
    projectId: 'platzi-flutter-e605a',
    authDomain: 'platzi-flutter-e605a.firebaseapp.com',
    storageBucket: 'platzi-flutter-e605a.appspot.com',
    measurementId: 'G-EZWQLWZ7DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSkYD4dhpA_F_zAXPAJLAPqLH002bG2ds',
    appId: '1:70488794227:android:63dc5e13fccb5885a6b606',
    messagingSenderId: '70488794227',
    projectId: 'platzi-flutter-e605a',
    storageBucket: 'platzi-flutter-e605a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb-OERBhb_4K_0_GqERuWjlgiWHjFqig0',
    appId: '1:70488794227:ios:0c72c005b96872b2a6b606',
    messagingSenderId: '70488794227',
    projectId: 'platzi-flutter-e605a',
    storageBucket: 'platzi-flutter-e605a.appspot.com',
    androidClientId: '70488794227-jrp4kar8v8a3r7ak453bc5v8jdvdbp68.apps.googleusercontent.com',
    iosClientId: '70488794227-082657ojhktcfn7fd6q6a62293iouo2q.apps.googleusercontent.com',
    iosBundleId: 'com.sena.johndiaz.frontSena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb-OERBhb_4K_0_GqERuWjlgiWHjFqig0',
    appId: '1:70488794227:ios:91dad3a4e3ad5c2aa6b606',
    messagingSenderId: '70488794227',
    projectId: 'platzi-flutter-e605a',
    storageBucket: 'platzi-flutter-e605a.appspot.com',
    androidClientId: '70488794227-jrp4kar8v8a3r7ak453bc5v8jdvdbp68.apps.googleusercontent.com',
    iosClientId: '70488794227-kpaegc86qj13g8voastcgbprp8gh12pl.apps.googleusercontent.com',
    iosBundleId: 'com.sena.johndiaz.frontSena.RunnerTests',
  );
}
